// Generated by Wrangler on Mon Apr 29 2024 12:50:15 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	SYSTEM: KVNamespace;
	CONVERSATION: KVNamespace;
	API_KEY: "DummyKey";
	AI: unknown;
}
